const files=["projects.csv","programs.csv","companies.csv","people.csv","institutions.csv","regulations.csv","sources.csv","evidence.csv","relationships.csv","observations.csv"];
const data={};const $=id=>document.getElementById(id);
function parseCSV(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==""))rows.push(row);row=[];cell="";}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??"").trim()])));}
async function load(name){const r=await fetch("data/"+name,{cache:"no-store"});if(!r.ok)throw Error(name+" tidak ditemukan");return parseCSV(await r.text());}
const esc=s=>(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function unique(field,list){return [...new Set(list.map(x=>x[field]).filter(Boolean))].sort();}
function renderProjects(){const q=$("projectSearch").value.toLowerCase().trim(),sec=$("sectorFilter").value,st=$("statusFilter").value;const list=(data.projects||[]).filter(p=>(!q||[p.name,p.province,p.sector].join(" ").toLowerCase().includes(q))&&(!sec||p.sector===sec)&&(!st||p.status===st));$("projectGrid").innerHTML=list.map(p=>`<a class="project-card" href="proyek-serang-panimbang.html"><span class="tag">${esc(p.sector)}</span><h3>${esc(p.name)}</h3><div class="meta">${esc(p.province)}</div><div class="card-bottom"><span>${esc(p.status)}</span><b>${p.investment_value?("Rp "+(Number(p.investment_value)/1e12).toLocaleString("id-ID",{minimumFractionDigits:3,maximumFractionDigits:3})+" T"):"—"}</b></div></a>`).join("")||'<div class="meta">Tidak ada hasil.</div>';}
function renderCompanies(){$("companyGrid").innerHTML=(data.companies||[]).map(c=>`<a class="company-card" href="perusahaan-a.html"><div class="company-type">${esc(c.entity_type)}</div><h3>${esc(c.legal_name)}</h3><div class="meta">${esc(c.role_default||"")}</div></a>`).join("")||'<div class="meta">Belum ada perusahaan.</div>';}
function renderPeople(){$("peopleGrid").innerHTML=(data.people||[]).map(p=>`<a class="person-card" href="orang-a.html"><span class="tag">${esc(p.verification_status||"DATA")}</span><h3>${esc(p.name)}</h3><div class="role">${esc(p.current_or_last_role||"")}</div><div class="linkline">${esc(p.current_or_last_company_id||"")}</div></a>`).join("")||'<div class="meta">Belum ada orang.</div>';}
function renderRules(){$("regulationList").innerHTML=(data.regulations||[]).map(r=>`<div class="rule"><span>${esc(r.year)}</span><div><b>${esc(r.title)}</b><small>${esc(r.notes||"")}</small></div><em>${esc(r.regulation_type)}</em></div>`).join("")||'<div class="meta">Belum ada regulasi.</div>';}
function buildFilters(){unique("sector",data.projects||[]).forEach(v=>$("sectorFilter").insertAdjacentHTML("beforeend",`<option>${esc(v)}</option>`));unique("status",data.projects||[]).forEach(v=>$("statusFilter").insertAdjacentHTML("beforeend",`<option>${esc(v)}</option>`));}
async function init(){try{for(const f of files)data[f.replace(".csv","")]=await load(f);$("statProjects").textContent=(data.projects||[]).length;$("statPrograms").textContent=(data.programs||[]).filter(x=>x.name&&x.name!=="[contoh program]").length;$("statCompanies").textContent=(data.companies||[]).length;$("statRelations").textContent=(data.relationships||[]).length;buildFilters();renderProjects();renderCompanies();renderPeople();renderRules();$("loadStatus").textContent="Dataset termuat";}catch(e){$("loadStatus").textContent="Gagal memuat dataset: "+e.message;console.error(e);}}
$("projectSearch").addEventListener("input",renderProjects);$("sectorFilter").addEventListener("change",renderProjects);$("statusFilter").addEventListener("change",renderProjects);
$("searchOpen").addEventListener("click",()=>{$("searchDialog").showModal();setTimeout(()=>$("globalSearch").focus(),40)});$("closeSearch").addEventListener("click",()=>$("searchDialog").close());$("searchDialog").addEventListener("click",e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
$("globalSearch").addEventListener("input",()=>{const q=$("globalSearch").value.toLowerCase().trim();const all=[...(data.projects||[]).map(x=>({t:"Proyek",n:x.name,m:x.province,u:"proyek-serang-panimbang.html"})),...(data.companies||[]).map(x=>({t:"Perusahaan",n:x.legal_name,m:x.role_default,u:"perusahaan-a.html"})),...(data.people||[]).map(x=>({t:"Orang",n:x.name,m:x.current_or_last_role,u:"orang-a.html"})),...(data.regulations||[]).map(x=>({t:"Aturan",n:x.title,m:x.year,u:"#aturan"}))];const hit=q?all.filter(x=>(x.n+" "+x.m).toLowerCase().includes(q)).slice(0,20):[];$("searchResults").innerHTML=hit.length?hit.map(x=>`<a class="result" href="${x.u}"><span>${esc(x.t)}</span><b>${esc(x.n)}</b><span>${esc(x.m)}</span></a>`).join(""):'<div class="meta">Ketik minimal satu kata.</div>';});
init();